### ISSUE TITLE
Error Download file from blob

### ISSUE THREAD

**Issue by py7hon** [scoute-dich/browser#373]
```
java.lang.IllegalArgumentException: Can not handle uri:: blob:https://nhentaidl.000webhostapp.com/2e697028-0544-4506-b2ee-9460d4d25505
	at android.app.DownloadManager$Request.checkUri(DownloadManager.java:702)
	at android.app.DownloadManager$Request.<init>(DownloadManager.java:686)
	at de.baumann.browser.Unit.BrowserUnit.download(BrowserUnit.java:187)
	at de.baumann.browser.Browser.NinjaDownloadListener$1.onClick(NinjaDownloadListener.java:43)
	at android.view.View.performClick(View.java:5207)
	at android.view.View$PerformClick.run(View.java:21177)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5441)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
```

**Comment by scoute-dich** [comment]
What's a "file from blob"? Have you a URL, from where I can download such a file?

**Comment by py7hon** [comment]
the file is a zip and the url

**Comment by scoute-dich** [comment]
Can I have a new link? the old one isn't working anymore.
