### ISSUE TITLE
Toolbar icon

### ISSUE THREAD

**Issue by islam2hamy** [scoute-dich/browser#489]
Step :
Hold the icon in the toolbar

App stop working

Os : miui 11
App v. : 7.3
Language : ar
Error log ;
"android.view.InflateException: Binary XML file line #22: Binary XML file line #22: Error inflating class <unknown>
Caused by: android.view.InflateException: Binary XML file line #22: Error inflating class <unknown>
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
	at android.view.LayoutInflater.createView(LayoutInflater.java:652)
	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:742)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:810)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:752)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:883)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:846)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:522)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:430)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
	at android.view.View.inflate(View.java:21046)
	at de.baumann.browser.activity.BrowserActivity.show_dialogFilter(BrowserActivity.java:1847)
	at de.baumann.browser.activity.BrowserActivity.lambda$initOmniBox$11$BrowserActivity(BrowserActivity.java:570)
	at de.baumann.browser.activity.-$$Lambda$BrowserActivity$ihJsbtR0miQUpX9se1sWT-xBXX8.onLongClick(lambda)
	at android.view.View.performLongClickInternal(View.java:5724)
	at android.view.View.performLongClick(View.java:5682)
	at android.view.View.performLongClick(View.java:5700)
	at android.view.View$CheckForLongPress.run(View.java:22434)
	at android.os.Handler.handleCallback(Handler.java:754)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6238)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
Caused by: android.content.res.Resources$NotFoundException: Drawable android:color/secondary_text_material_light with resource ID #0x106015c
Caused by: android.content.res.Resources$NotFoundException: File res/color/secondary_text_material_light.xml from drawable resource ID #0x106015c
	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:748)
	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:585)
	at android.content.res.MiuiResourcesImpl.loadDrawable(MiuiResourcesImpl.java:328)
	at android.content.res.Resources.loadDrawable(Resources.java:876)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:930)
	at android.view.View.<init>(View.java:4210)
	at android.view.View.<init>(View.java:4117)
	at android.view.View.<init>(View.java:4096)
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
	at android.view.LayoutInflater.createView(LayoutInflater.java:652)
	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:742)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:810)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:752)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:883)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:846)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:522)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:430)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
	at android.view.View.inflate(View.java:21046)
	at de.baumann.browser.activity.BrowserActivity.show_dialogFilter(BrowserActivity.java:1847)
	at de.baumann.browser.activity.BrowserActivity.lambda$initOmniBox$11$BrowserActivity(BrowserActivity.java:570)
	at de.baumann.browser.activity.-$$Lambda$BrowserActivity$ihJsbtR0miQUpX9se1sWT-xBXX8.onLongClick(lambda)
	at android.view.View.performLongClickInternal(View.java:5724)
	at android.view.View.performLongClick(View.java:5682)
	at android.view.View.performLongClick(View.java:5700)
	at android.view.View$CheckForLongPress.run(View.java:22434)
	at android.os.Handler.handleCallback(Handler.java:754)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6238)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #20: <item> tag requires a 'drawable' attribute or child tag defining a drawable
	at android.graphics.drawable.StateListDrawable.inflateChildElements(StateListDrawable.java:183)
	at android.graphics.drawable.StateListDrawable.inflate(StateListDrawable.java:116)
	at android.graphics.drawable.DrawableInflater.inflateFromXml(DrawableInflater.java:130)
	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1229)
	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1202)
	at android.content.res.ResourcesImpl.createFromXml(ResourcesImpl.java:1307)
	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:735)
	... 34 more
"

**Comment by scoute-dich** [comment]
Which Icon? There are three. With holding you mean long pressing?

**Comment by islam2hamy** [comment]
<a href="https://ibb.co/4Kcv5VJ"><img src="https://i.ibb.co/TYZjFgr/IMG.jpg" alt="IMG" border="0"></a>

**Comment by islam2hamy** [comment]
Long pressing

**Comment by scoute-dich** [comment]
Btw: Thanks for the logcats.
