### ISSUE TITLE
Crash when opening new Tab

### ISSUE THREAD

**Issue by woheller69** [scoute-dich/browser#587]
Just had a crash when I opened a new tab:
Logcat says:

--------- beginning of crash
07-11 18:47:31.936  8844  8844 E AndroidRuntime: FATAL EXCEPTION: main
07-11 18:47:31.936  8844  8844 E AndroidRuntime: Process: de.baumann.browser, PID: 8844
07-11 18:47:31.936  8844  8844 E AndroidRuntime: java.lang.NullPointerException
07-11 18:47:31.936  8844  8844 E AndroidRuntime: 	at android.net.WebAddress.<init>(WebAddress.java:77)
07-11 18:47:31.936  8844  8844 E AndroidRuntime: 	at Wm.a(chromium-TrichromeWebViewGoogle.aab-stable-447212033:1)
07-11 18:47:31.936  8844  8844 E AndroidRuntime: 	at Wm.getCookie(chromium-TrichromeWebViewGoogle.aab-stable-447212033:1)
07-11 18:47:31.936  8844  8844 E AndroidRuntime: 	at de.baumann.browser.activity.BrowserActivity.updateOmniBox(BrowserActivity.java:1281)
07-11 18:47:31.936  8844  8844 E AndroidRuntime: 	at de.baumann.browser.activity.BrowserActivity.lambda$initOmniBox$12$BrowserActivity(BrowserActivity.java:617)
07-11 18:47:31.936  8844  8844 E AndroidRuntime: 	at de.baumann.browser.activity.-$$Lambda$BrowserActivity$aJrkxM6Es5HUbpW2KsBE1SVgF2s.onFocusChange(Unknown Source:2)
07-11 18:47:31.936  8844  8844 E AndroidRuntime: 	at android.view.View.onFocusChanged(View.java:8550)
07-11 18:47:31.936  8844  8844 E AndroidRuntime: 	at android.widget.TextView.onFocusChanged(TextView.java:11920)
07-11 18:47:31.936  8844  8844 E AndroidRuntime: 	at android.widget.EditText.onFocusChanged(EditText.java:254)
07-11 18:47:31.936  8844  8844 E AndroidRuntime: 	at android.widget.AutoCompleteTextView.onFocusChanged(AutoCompleteTextView.java:1173)
07-11 18:47:31.936  8844  8844 E AndroidRuntime: 	at android.view.View.clearFocusInternal(View.java:8387)
07-11 18:47:31.936  8844  8844 E AndroidRuntime: 	at android.view.View.clearFocus(View.java:8366)
07-11 18:47:31.936  8844  8844 E AndroidRuntime: 	at de.baumann.browser.activity.BrowserActivity.updateOmniBox(BrowserActivity.java:1274)
07-11 18:47:31.936  8844  8844 E AndroidRuntime: 	at de.baumann.browser.activity.BrowserActivity.updateProgress(BrowserActivity.java:1333)
07-11 18:47:31.936  8844  8844 E AndroidRuntime: 	at de.baumann.browser.view.NinjaWebView.update(NinjaWebView.java:256)
07-11 18:47:31.936  8844  8844 E AndroidRuntime: 	at de.baumann.browser.browser.NinjaWebChromeClient.onProgressChanged(NinjaWebChromeClient.java:28)
07-11 18:47:31.936  8844  8844 E AndroidRuntime: 	at Cv0.d(chromium-TrichromeWebViewGoogle.aab-stable-447212033:3)
07-11 18:47:31.936  8844  8844 E AndroidRuntime: 	at h9.handleMessage(chromium-TrichromeWebViewGoogle.aab-stable-447212033:53)
07-11 18:47:31.936  8844  8844 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
07-11 18:47:31.936  8844  8844 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:237)
07-11 18:47:31.936  8844  8844 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8154)
07-11 18:47:31.936  8844  8844 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-11 18:47:31.936  8844  8844 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
07-11 18:47:31.936  8844  8844 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

In my current version:
de.baumann.browser.activity.BrowserActivity.updateOmniBox(BrowserActivity.java:1281)
does: manager.getCookie(ninjaWebView.getUrl());

BrowserActivity(BrowserActivity.java:617)
does: updateOmniBox();

**Comment by woheller69** [comment]
Just had a crash again. Somehow manager.getCookie(ninjaWebView.getUrl()); 
throws a null pointer exception. Maybe ninjaWebView.getUrl() delivers null?
