### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.contains(java.lang.CharSequence)' on a null object reference

### ISSUE THREAD

**Issue by Kita2345** [scoute-dich/browser#642]
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.contains(java.lang.CharSequence)' on a null object reference
	at de.baumann.browser.activity.BrowserActivity.lambda$initOmniBox$12$BrowserActivity(BrowserActivity.java:606)
	at de.baumann.browser.activity.-$$Lambda$BrowserActivity$aJrkxM6Es5HUbpW2KsBE1SVgF2s.onFocusChange(lambda)
	at android.view.View.onFocusChanged(View.java:5182)
	at android.widget.TextView.onFocusChanged(TextView.java:7980)
	at android.widget.AutoCompleteTextView.onFocusChanged(AutoCompleteTextView.java:1015)
	at android.view.View.handleFocusGainInternal(View.java:4938)
	at android.view.View.requestFocusNoSearch(View.java:7648)
	at android.view.View.requestFocus(View.java:7627)
	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2663)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:2619)
	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2663)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:2619)
	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2663)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:2619)
	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2663)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:2619)
	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2663)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:2619)
	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2663)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:2619)
	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2663)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:2619)
	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2663)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:2619)
	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2663)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:2622)
	at android.view.View.requestFocus(View.java:7594)
	at android.view.View.requestFocus(View.java:7573)
	at android.view.View.rootViewRequestFocus(View.java:5082)
	at android.view.ViewGroup.removeAllViewsInLayout(ViewGroup.java:4360)
	at android.view.ViewGroup.removeAllViews(ViewGroup.java:4289)
	at de.baumann.browser.activity.BrowserActivity.showAlbum(BrowserActivity.java:412)
	at de.baumann.browser.view.AlbumItem.lambda$deactivate$3$AlbumItem(AlbumItem.java:66)
	at de.baumann.browser.view.-$$Lambda$AlbumItem$ZyxGqxWHpmA2F2LoV3g1zPtREuo.onClick(lambda)
	at android.view.View.performClick(View.java:4756)
	at android.view.View$PerformClick.run(View.java:19761)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5264)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695)

**Comment by woheller69** [comment]
instead of

       assert url != null;
                if (url.contains("about:blank")) {
                    omniBox_text.setText("");
                } else {

we should use:

                if (url==null || url.contains("about:blank")) {
                    omniBox_text.setText("");
                } else {

**Comment by scoute-dich** [comment]
[app-debug.apk.zip](https://github.com/scoute-dich/browser/files/6945908/app-debug.apk.zip)
Here someone can test ...

**Comment by scoute-dich** [comment]
[app-debug.apk.zip](https://github.com/scoute-dich/browser/files/6949675/app-debug.apk.zip)

**Comment by scoute-dich** [comment]
If the problem persists in the latest version, please reopen or create a new issue.
