### ISSUE TITLE
Crash with latest snapshot

### ISSUE THREAD

**Issue by woheller69** [scoute-dich/browser#713]
No idea where exactly it comes from...
But it seems to have to do with CompleteAdapter and change of adapter without notifyDataSetChanged.
Did you recently make any changes there?

2021-11-11 16:44:21.624 12357-12357/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.baumann.browser, PID: 12357
    java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes. [in ListView(-1, class android.widget.DropDownListView) with Adapter(class de.baumann.browser.view.CompleteAdapter)]
        at android.widget.ListView.layoutChildren(ListView.java:1717)
        at android.widget.AbsListView.onLayout(AbsListView.java:2202)
        at android.view.View.layout(View.java:22466)
        at android.view.ViewGroup.layout(ViewGroup.java:6304)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22466)
        at android.view.ViewGroup.layout(ViewGroup.java:6304)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22466)
        at android.view.ViewGroup.layout(ViewGroup.java:6304)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3157)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2614)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1745)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7768)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
        at android.view.Choreographer.doCallbacks(Choreographer.java:791)
        at android.view.Choreographer.doFrame(Choreographer.java:726)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

**Comment by scoute-dich** [comment]
I just set two methods to be synchronized. I have those issue also since months. But I can't really reproduce it. It seems to happen when you type fast or delete text in the input very fast.

Otherwise I made no changes there.

**Comment by woheller69** [comment]
In other complete adapters I find publishResults like this:


            @Override
            protected void publishResults(CharSequence constraint, FilterResults results) {

                if (results != null && results.count > 0) {
                    // The API returned at least one result, update the data.
                    mResultList = (ArrayList<AutocompletePrediction>) results.values;
                    notifyDataSetChanged();
                } else {
                    // The API did not return any results, invalidate the data set.
                    notifyDataSetInvalidated();
                }
            }

ours looks like:

        @Override
        protected synchronized void publishResults (CharSequence constraint, FilterResults results) {
            notifyDataSetChanged();
        }
    }

just notifyDataSetChanged without conditions.

Not sure it this has to do with the problem, just an idea...

**Comment by scoute-dich** [comment]
I'll test this later.

**Comment by woheller69** [comment]
"Synchronized" is probably not the solution, especially as we are overriding methods.
Then already the methods of the super class should use synchronized.

**Comment by scoute-dich** [comment]
I tried it, but not much success.

**Comment by woheller69** [comment]
Can you try the above commit? I do not have the problem very often.
But I think I found a possible reason.
The resultList was modified in performFiltering() already and not only in publishResults() together with notifyDataSetChanged.
Now I introduced a workList in performFiltering() and this is written to resultList in publishResults()

**Comment by woheller69** [comment]
I think you need to revert your latest commit before merging

**Comment by woheller69** [comment]
I am quite sure this is the solution. It was the only place where the adapter was changed without immediate notifyDataSetChanged()

**Comment by scoute-dich** [comment]
It seems to work in most cases. But it's still not 100%.

**Comment by woheller69** [comment]
do you have a logcat?

**Comment by woheller69** [comment]
I only have it rarely and only on my small development phone. Not on my tablet...

**Comment by woheller69** [comment]
maybe make getCount, getItem, and publishResults synchronized?

Or put

    synchronized (resultItem){

    }

around the inner parts of these 3 methods. Maybe e.g. getCount is called after resultList is set in publishResults but before notifyDataSetChanged?

**Comment by woheller69** [comment]
just looked at your code
you still have 

    resultList.add(item)

in line 49

**Comment by woheller69** [comment]
and also lines 54, 58,59 need to be deleted

**Comment by woheller69** [comment]
just copy/paste the whole completeAdapter file from my commit

**Comment by woheller69** [comment]
resultList must not be used anywhere in performFiltering
