### ISSUE TITLE
Crashing - Android 5.x.x 

### ISSUE THREAD

**Issue by Dvaderfun** [scoute-dich/browser#8]
On Android 5.x.x app crashes after inro. 
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Paint.getAlpha()' on a null object reference
	at android.graphics.drawable.NinePatchDrawable.draw(NinePatchDrawable.java:250)
	at android.graphics.drawable.LayerDrawable.draw(LayerDrawable.java:517)
	at android.widget.ProgressBar.drawTrack(ProgressBar.java:1669)
	at android.widget.ProgressBar.onDraw(ProgressBar.java:1636)
	at android.view.View.draw(View.java:15247)
	at android.view.View.updateDisplayListIfDirty(View.java:14183)
	at android.view.View.getDisplayList(View.java:14205)
	at android.view.View.draw(View.java:14975)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
	at android.view.View.updateDisplayListIfDirty(View.java:14178)
	at android.view.View.getDisplayList(View.java:14205)
	at android.view.View.draw(View.java:14975)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
	at android.view.View.updateDisplayListIfDirty(View.java:14178)
	at android.view.View.getDisplayList(View.java:14205)
	at android.view.View.draw(View.java:14975)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
	at android.view.View.updateDisplayListIfDirty(View.java:14178)
	at android.view.View.getDisplayList(View.java:14205)
	at android.view.View.draw(View.java:14975)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
	at android.view.View.updateDisplayListIfDirty(View.java:14178)
	at android.view.View.getDisplayList(View.java:14205)
	at android.view.View.draw(View.java:14975)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
	at android.view.View.updateDisplayListIfDirty(View.java:14178)
	at android.view.View.getDisplayList(View.java:14205)
	at android.view.View.draw(View.java:14975)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
	at android.view.View.updateDisplayListIfDirty(View.java:14178)
	at android.view.View.getDisplayList(View.java:14205)
	at android.view.View.draw(View.java:14975)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
	at android.view.View.draw(View.java:15250)
	at android.widget.FrameLayout.draw(FrameLayout.java:598)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2906)
	at android.view.View.updateDisplayListIfDirty(View.java:14183)
	at android.view.View.getDisplayList(View.java:14205)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:273)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:279)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:318)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2536)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2352)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1982)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5891)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
	at android.view.Choreographer.doFrame(Choreographer.java:550)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5294)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)

**Comment by scoute-dich** [comment]
Hi,

thanks for reporting. Since I have only a "Nougat" device, can you test the attached apk-file? If compressed it as zip-file, since apk-files aren't allowed as attachement.

Regards
Gaukler Faun

[app-release.apk.zip](https://github.com/scoute-dich/browser/files/885847/app-release.apk.zip)

**Comment by rjc** [comment]
APK file *is* as ZIP file - just change the extension :^)

**Comment by scoute-dich** [comment]
Yes I know. Two possibilities with same result. But since I work mainly with the mouse instead of keyboard it's less work to do a right click and pack as zip...

**Comment by Dvaderfun** [comment]
@scoute-dich working perfectly. What was the problem?

**Comment by scoute-dich** [comment]
I had a transparent background for the progressbar while loading websites. I changed it to a solid color.

Thanks again for reporting the bug. O only have a device with nougat installed. So I wasn't aware of this bug.
