### ISSUE TITLE
crash on every start, Android 11

### ISSUE THREAD

**Issue by xandro0777** [scoute-dich/browser#847]
Hi, I have freshly installed FOSS Browser on a new Android 11 Realme 8 device and it crashes on every start attempt, by it from launcher or by invoking an URL.

I have captured this log, can provide more context if needed:
```
01-20 19:41:39.868 12211 12211 E AndroidRuntime: FATAL EXCEPTION: main
01-20 19:41:39.868 12211 12211 E AndroidRuntime: Process: de.baumann.browser, PID: 12211
01-20 19:41:39.868 12211 12211 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{de.baumann.browser/de.baumann.browser.activity.BrowserActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void de.baumann.browser.view.NinjaWebView.setProfileDefaultValues()' on a null object reference
01-20 19:41:39.868 12211 12211 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3745)
01-20 19:41:39.868 12211 12211 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3913)
01-20 19:41:39.868 12211 12211 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
01-20 19:41:39.868 12211 12211 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
01-20 19:41:39.868 12211 12211 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
01-20 19:41:39.868 12211 12211 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2338)
01-20 19:41:39.868 12211 12211 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-20 19:41:39.868 12211 12211 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:255)
01-20 19:41:39.868 12211 12211 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8232)
01-20 19:41:39.868 12211 12211 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-20 19:41:39.868 12211 12211 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
01-20 19:41:39.868 12211 12211 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
01-20 19:41:39.868 12211 12211 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void de.baumann.browser.view.NinjaWebView.setProfileDefaultValues()' on a null object reference
01-20 19:41:39.868 12211 12211 E AndroidRuntime: 	at de.baumann.browser.activity.BrowserActivity.onCreate(BrowserActivity.java:315)
01-20 19:41:39.868 12211 12211 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8151)
01-20 19:41:39.868 12211 12211 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8135)
01-20 19:41:39.868 12211 12211 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
01-20 19:41:39.868 12211 12211 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3714)
01-20 19:41:39.868 12211 12211 E AndroidRuntime: 	... 11 more
01-20 19:41:39.877  1670  2394 W ActivityTaskManager:   Force finishing activity de.baumann.browser/.activity.BrowserActivity
```

TIA

**Comment by scoute-dich** [comment]
Sorry, I was offline a time. I'll release an update this weekend. Then this should be fixed. 😉
