### ISSUE TITLE
Crash in file page

### ISSUE THREAD

**Issue by lishoujun** [scoute-dich/browser#86]
I open file  then go to ... (parent folder ) 
Close current tab .
new a file tab
Crash

**Comment by lishoujun** [comment]
02-04 22:09:14.867 20290-20290/de.baumann.browser I/hwaps: JNI_OnLoad
02-04 22:09:17.295 20290-20290/de.baumann.browser E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: de.baumann.browser, PID: 20290
                                                                    java.lang.NullPointerException: Attempt to get length of null array
                                                                        at de.baumann.browser.Activity.BrowserActivity.initFEList(BrowserActivity.java:1379)
                                                                        at de.baumann.browser.Activity.BrowserActivity.addAlbum(BrowserActivity.java:1807)
                                                                        at de.baumann.browser.Activity.BrowserActivity.access$2200(BrowserActivity.java:135)
                                                                        at de.baumann.browser.Activity.BrowserActivity$27.onClick(BrowserActivity.java:993)
                                                                        at android.view.View.performClick(View.java:5646)
                                                                        at android.view.View$PerformClick.run(View.java:22473)
                                                                        at android.os.Handler.handleCallback(Handler.java:761)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                        at android.os.Looper.loop(Looper.java:156)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6523)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
02-04 22:09:17.338 20290-20290/de.baumann.browser I/Process: Sending signal. PID: 20290 SIG: 9

**Comment by scoute-dich** [comment]
Yes, and already merged. Thank you. This is the kind of issue, which you don't see, until somebody retorts it. So thanks again.
